### ISSUE TITLE
The scripts must be aware of Docker container restart.

### ISSUE THREAD

**Issue by Koubek** [NAVDOCKER/GENERIC#3]
All involved scripts (executed withing the last `CMD` => `C:\Run\start.ps1`) must be aware of the possibility the container could be restarted. This command is executed always.

You can restart any container:
`docker restart [container]`

[Docker Restart Policies](https://docs.docker.com/engine/reference/run/#restart-policies-restart)
For example: `docker run --restart=always`

**Comment by freddydk** [comment]
Fixed
